import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/components/theme-provider";
import { SessionProvider } from "next-auth/react";
import Header from "@/components/custom/Header";
import SideNavBar from "@/components/custom/SideNavBar";
import { Separator } from "@/components/ui/separator";
import { auth } from "../../auth";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {session ? (
            <SessionProvider>
              <main className="h-screen grid grid-rows-[auto,1fr] ">
                <header className="col-span-full bg-muted/40">
                  <div className="grid grid-cols-12 gap-4 justify-normal content-center m-2">
                    <Header />
                  </div>
                  <Separator />
                </header>
                <div className="grid grid-cols-[auto,1fr] gap-4 ">
                  <aside className="w-72">
                    <SideNavBar />
                  </aside>
                  <section className="p-5 mx-5 overflow-auto ">
                    {children}
                  </section>
                </div>
              </main>
            </SessionProvider>
          ) : (
            <SessionProvider>{children}</SessionProvider>
          )}
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
