import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/components/theme-provider";
import { SessionProvider } from "next-auth/react";
import Header from "@/components/custom/Header";
import SideNavBar from "@/components/custom/SideNavBar";
import { Separator } from "@/components/ui/separator";
import { auth } from "../../auth";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {session ? (
            <SessionProvider>
              <main className="h-screen w-screen grid grid-rows-[auto,1fr]">
                <header className="col-span-full bg-muted/40 fixed w-full z-10">
                  <div className="grid grid-cols-12 gap-4 justify-normal content-center p-2.5 backdrop-blur-sm shadow-lg">
                    <Header />
                  </div>
                  <Separator />
                </header>
                <div className="grid grid-cols-5 gap-4 pt-20 justify-items-start">
                  <div>
                    <aside className="w-72 fixed h-full z-10 bg-muted/20 shadow-lg">
                      <SideNavBar />
                    </aside>
                  </div>
                 <div className="col-span-4 w-full">
                  <section className=" overflow-auto">
                    {children}
                  </section>
                 </div>

                </div>
              </main>
            </SessionProvider>
          ) : (
            <SessionProvider>{children}</SessionProvider>
          )}
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
